window.NB_MOCK = {
  user: {
    name: "小赵",
    community: "梧桐里",
    credit: 96,
  },
  presets: [
    "今晚 7 点前帮我从小区门口取一个快递，送到 3 栋楼下，10 元以内。",
    "周六下午想找两位邻居一起去河堤散步，顺路拍几张花草照片。",
    "明天上午想借一个小推车，搬两箱书到 5 栋门口。",
  ],
  quickActions: [
    {
      id: "errand",
      title: "跑腿互助",
      subtitle: "宠物照顾、跑腿代办、简单维修",
      tone: "yellow",
      art: "mail",
      compose: true,
    },
    {
      id: "share",
      title: "物品共享",
      subtitle: "东西有偿借，省钱又环保",
      tone: "blue",
      art: "calendar",
      target: "discover",
    },
    {
      id: "circle",
      title: "邻里动态",
      subtitle: "邻里街坊灌水平台",
      tone: "purple",
      art: "sofa",
      target: "discover",
    },
  ],
  nearbyPosts: [
    {
      id: "p-1",
      name: "小鱼丸",
      time: "2分钟前",
      avatar: "yu",
      text: "今天在小区花园发现一只超可爱的小猫，蹲在绣球旁边晒太阳。",
      visual: "pet",
      meta: "梧桐里花园",
      tag: "日常发现",
    },
    {
      id: "p-2",
      name: "阿树",
      time: "1小时前",
      avatar: "shu",
      text: "周六想组队去河堤散步，路线轻松，已经有 3 人报名。",
      visual: null,
      meta: "3人已报名",
      tag: "周末活动",
    },
    {
      id: "p-3",
      name: "安安",
      time: "3小时前",
      avatar: "an",
      text: "楼下新开的咖啡角很安静，推荐给大家，适合等人和取还小物。",
      visual: "coffee",
      meta: "北门 60 米",
      tag: "附近推荐",
    },
  ],
  discoverCards: [
    { title: "傍晚散步局", text: "今天 19:30，梧桐步道慢走 30 分钟。", count: "5人感兴趣" },
    { title: "共享工具角", text: "小推车、折叠梯、打气筒今天可借。", count: "4件可用" },
    { title: "邻里问答", text: "谁知道 2 栋快递柜临时密码怎么查？", count: "8条回复" },
  ],
  tools: [
    { id: "tool-1", name: "小推车", owner: "3 栋管家", place: "3 栋大厅", time: "全天可借", rule: "2 小时内免费", price: 0, icon: "cart" },
    { id: "tool-2", name: "折叠梯", owner: "林小乔", place: "5 栋", time: "明天 9:00 后", rule: "实名确认", price: 5, icon: "ladder" },
    { id: "tool-3", name: "工具箱", owner: "物业维修间", place: "物业中心", time: "工作日 9:00-18:00", rule: "物业见证取还", price: 0, icon: "box" },
  ],
};
