window.NB_MOCK = {
  user: {
    name: "小赵",
    community: "梧桐里",
    credit: 96,
  },
  presets: [
    "今晚 7 点前帮我从小区门口取一个快递，送到 3 栋楼下，10 元以内。",
    "周六下午想找两位邻居一起去河堤散步，顺路拍几张花草照片。",
    "明天上午想借一个小推车，搬两箱书到 5 栋门口。",
  ],
  quickActions: [
    {
      id: "errand",
      title: "跑腿互助",
      subtitle: "宠物照顾、跑腿代办、简单维修",
      tone: "yellow",
      art: "mail",
      target: "errand",
    },
    {
      id: "share",
      title: "物品共享",
      subtitle: "东西有偿借，省钱又环保",
      tone: "blue",
      art: "calendar",
      target: "discover",
    },
    {
      id: "circle",
      title: "邻里动态",
      subtitle: "邻里街坊灌水平台",
      tone: "purple",
      art: "sofa",
      target: "circle",
    },
  ],
  errandServices: [
    {
      id: "pickup",
      ruleId: "pickup",
      title: "代取快递 顺手捎带",
      desc: "快递站、门口柜、小区门房取件，送到单元楼下或家门口。",
      price: "1.5 元/件",
      reward: "奖 3 点活跃值",
      risk: "低风险",
      fields: ["收件人", "手机后四位", "房间号", "取件码"],
      note: "建议备注最新收件人信息，取件完成后拍照留痕。",
    },
    {
      id: "trash",
      ruleId: "delivery",
      title: "门口垃圾倾倒 + 分类",
      desc: "顺手带走门口垃圾，按社区分类要求投放。",
      price: "2 元/次",
      reward: "奖 3 点活跃值",
      risk: "低风险",
      fields: ["楼栋房号", "垃圾位置", "可取时间"],
      note: "请提前扎紧垃圾袋，不接厨余渗漏或危险物品。",
    },
    {
      id: "delivery",
      ruleId: "delivery",
      title: "周边取送物品",
      desc: "取送餐食、衣物、生活用品，覆盖小区周边 1 公里。",
      price: "3 元/次",
      reward: "奖 3 点活跃值",
      risk: "低风险",
      fields: ["取件点", "送达点", "物品说明"],
      note: "贵重物品建议走平台托管并拍照确认。",
    },
    {
      id: "buy",
      ruleId: "delivery",
      title: "买东西 或 谁家有",
      desc: "不方便外出时，请邻居顺路买菜、药品或生活小物。",
      price: "5 元起",
      reward: "奖 3 点活跃值",
      risk: "中低风险",
      fields: ["购买清单", "预算", "送达时间"],
      note: "涉及代垫费用时，建议上传小票并平台结算。",
    },
    {
      id: "meal",
      ruleId: "meal",
      title: "带我一份饭",
      desc: "邻居做饭或外出就餐时，顺手带一份健康餐。",
      price: "30 元/人餐",
      reward: "奖 4 点活跃值",
      risk: "中低风险",
      fields: ["联系人", "大致时间", "忌口备注"],
      note: "请注明忌口、送达方式和是否需要送上门。",
    },
    {
      id: "repair",
      ruleId: "repair",
      title: "简单维修与临时搭把手",
      desc: "换灯泡、拧螺丝、搬轻物等低风险上门协助。",
      price: "8 元起",
      reward: "奖 5 点活跃值",
      risk: "中风险",
      fields: ["维修内容", "上门时间", "是否有工具"],
      note: "涉及入户隐私和工具使用，优先选择高信用邻居。",
    },
  ],
  errandServiceRules: [
    {
      id: "pickup",
      title: "代取快递规则",
      summary: "适用于快递站、门口柜、小区门房的低风险代取，重点是信息准确、尺寸清楚、完成留痕。",
      standards: [
        "中小件：最长边低于 50CM，或重量小于 2 斤，可按普通代取处理。",
        "大件：最长边超过 50CM，需提前说明是否需要推车或两人协助。",
        "重包裹：重量超过 5 斤必须备注，超过 30 斤建议改为专业搬运。",
      ],
      flow: [
        "下单填写收件人、手机号后四位、取件码、房号和可送达时间。",
        "接单者到站点核对信息，取件后拍摄包裹外观，避免错拿。",
        "送到指定门口或单元楼下后上传完成照片，需求方确认后结算。",
      ],
      warnings: [
        "不接生鲜破损、危险品、贵重物品或明显需要专业搬运的包裹。",
        "取件信息缺失时，接单者可拒绝取件，避免误取纠纷。",
      ],
    },
    {
      id: "delivery",
      title: "跑腿取送规则",
      summary: "适用于小区周边 1 公里内的轻量取送、买东西、临时递送，要求路线清晰、费用清晰。",
      standards: [
        "取送范围默认覆盖本小区及周边 1 公里，超出范围需双方确认加价。",
        "代买物品需写清清单、预算、可替代选项和是否需要小票。",
        "涉及垫付时建议走平台托管或上传票据，不鼓励私下转账。",
      ],
      flow: [
        "下单填写取件点、送达点、物品说明、预算和期望时间。",
        "接单后开启位置记录，取到物品后拍照确认。",
        "送达后上传完成照片，若有垫付费用需附小票或支付截图。",
      ],
      warnings: [
        "不承接烟酒、处方药、现金、有价证券等敏感物品。",
        "不允许擅自改变路线、延迟交付或转交给未接单人员。",
      ],
    },
    {
      id: "meal",
      title: "做饭 / 送饭规则",
      summary: "适用于邻居顺手带饭、家常饭预订和短距离送饭，核心是卫生、忌口和送达方式说清楚。",
      standards: [
        "下单必须备注人数、忌口、过敏源、口味偏好和期望送达时间。",
        "家常饭默认不等同餐饮商家服务，需清楚标注是否含食材和餐具。",
        "送饭默认送到门口或楼下，不建议进入卧室等私密空间。",
      ],
      flow: [
        "需求方确认菜单、份数、送达方式和费用。",
        "接单者完成后拍摄餐食包装和送达位置。",
        "需求方确认收到后再结算，出现食品异常优先平台沟通。",
      ],
      warnings: [
        "婴幼儿、病人、严重过敏人群用餐建议选择专业渠道。",
        "不接临期、变质、来源不明食材，不夸大健康功效。",
      ],
    },
    {
      id: "repair",
      title: "简单维修规则",
      summary: "仅限低风险、小工具类协助，如换灯泡、拧螺丝、搬轻物、检查简单故障。",
      standards: [
        "允许：换灯泡、拧螺丝、安装小挂钩、搬轻物、查看简单家电外观故障。",
        "禁止：燃气、电路拆改、高空作业、防水改造、承重墙打孔等专业高危项目。",
        "入户服务建议白天进行，优先选择高信用、实名和有技能证书的邻居。",
      ],
      flow: [
        "下单上传问题照片，写清工具是否自备、入户时间和是否有家人在场。",
        "接单者到场前确认服务边界，不确定的故障应建议找专业师傅。",
        "完成前后各拍一张照片，涉及材料费需上传票据。",
      ],
      warnings: [
        "单身或老人独居场景建议绑定家属或物业见证。",
        "发现安全隐患时应停止互助服务，转为专业维修。",
      ],
    },
  ],
  highRiskServiceRules: [
    {
      id: "child_pickup",
      title: "接孩子规则",
      level: "最高风险服务",
      points: [
        "必须完成监护人电子授权，填写孩子姓名、学校班级、交接点、衣着特征和紧急联系人。",
        "接单者必须通过实名、人脸、居住核验和无犯罪记录复核，前 5 单低风险全好评后才开放权限。",
        "到校门口、送到单元楼下均需拍照留痕，全程记录 GPS，偏离路线超过 3 分钟触发预警。",
        "禁止绕路、逗留、带孩子去商店或进入接单者家中。",
      ],
    },
    {
      id: "elder_care",
      title: "老人陪护规则",
      level: "高风险入户服务",
      points: [
        "老人下单必须绑定直系紧急联系人，服务消息同步推送家属。",
        "独居老人陪护默认仅开放 9:00-18:00，认知不清或阿尔茨海默症老人需家属在场。",
        "进门和离开需拍公共区域照片，必要时开启平台录音留存。",
        "身体风险需前置告知，如高血压、腿脚不便、认知障碍等。",
      ],
    },
    {
      id: "pet_care",
      title: "遛宠规则",
      level: "中高风险服务",
      points: [
        "下单需填写宠物品种、年龄、疫苗情况、牵引习惯和是否会攻击人或同类。",
        "全程开启 GPS，完成时上传宠物回到指定地点照片。",
        "禁止私自带宠物长时间外出、转交他人或进入非约定场所。",
        "宠物伤人、走失、突发疾病按平台协议、保险和责任划分处理。",
      ],
    },
    {
      id: "home_repair",
      title: "上门维修规则",
      level: "高风险入户服务",
      points: [
        "涉及电路、燃气、高空、承重结构、防水改造等项目必须转专业维修。",
        "接单者需完成实名、人脸、居住核验，具备电工证、维修证等可获得优先展示。",
        "上门前确认是否有第三人在场，完成前后拍照，材料费必须票据留存。",
        "出现争议或安全风险时暂停服务，走平台客服、物业或保险流程。",
      ],
    },
  ],
  nearbyPosts: [
    {
      id: "seed-errand-ask-1",
      name: "王启明",
      time: "刚刚",
      avatar: "assets/avatars/resident-man.png",
      title: "下班前能帮带一件中通快递吗？ #跑腿互助",
      text: "我今晚 6 点半才能到家，快递站 7 点关门，想请同小区邻居顺手帮带到 6 栋门口，愿意付 8 元辛苦费。",
      count: "12条回复",
      tag: "求帮助",
    },
    {
      id: "seed-errand-offer-1",
      name: "林晓悦",
      time: "18分钟前",
      avatar: "assets/avatars/teacher-woman.png",
      title: "我在菜鸟驿站附近，可以顺路帮带 #跑腿互助",
      text: "今天 18:20 从东门菜鸟驿站回 3 栋，轻小件可以顺手带，免费帮忙，备注楼栋和取件码就行。",
      count: "9人想联系",
      tag: "帮助",
    },
    {
      id: "seed-share-offer-1",
      name: "陈海宁",
      time: "35分钟前",
      avatar: "assets/avatars/veteran-man.png",
      title: "折叠小推车今晚可借 #物品共享",
      text: "家里有一辆承重 60kg 的折叠小推车，搬箱子、拿桶装水都方便，今晚 20:00 前可借，记得当天归还。",
      count: "6人收藏",
      tag: "帮助",
    },
    {
      id: "seed-chat-1",
      name: "沈清禾",
      time: "24分钟前",
      avatar: "assets/avatars/cafe-woman.png",
      title: "今晚楼下桂花香好明显 #邻友圈",
      text: "刚从南门散步回来，桂花一路都很香。有没有邻居也喜欢晚上绕小区慢走？可以约个不赶时间的散步局。",
      count: "15条评论",
      tag: "邻友圈",
    },
    {
      id: "seed-share-ask-1",
      name: "赵明远",
      time: "1小时前",
      avatar: "assets/avatars/outdoor-man.png",
      title: "想借一把电钻装窗帘 #物品共享",
      text: "周六上午想装两根窗帘杆，想借电钻和 6mm 钻头，用完会擦干净还回去，可以带一杯咖啡感谢。",
      count: "4条回复",
      tag: "求帮助",
    },
    {
      id: "seed-circle-offer-1",
      name: "刘雨桐",
      time: "2小时前",
      avatar: "assets/avatars/pet-woman.png",
      title: "周六亲子跳蚤小摊报名 #邻里动态",
      text: "本周六下午在中心花园摆亲子小摊，旧书、玩具、手作都可以带来，想一起组织的邻居可以留言。",
      count: "18人感兴趣",
      tag: "帮助",
    },
  ],
  discoverCards: [
    { title: "傍晚散步局", text: "今天 19:30，梧桐步道慢走 30 分钟。", count: "5人感兴趣" },
    { title: "共享工具角", text: "小推车、折叠梯、打气筒今天可借。", count: "4件可用" },
    { title: "邻里问答", text: "谁知道 2 栋快递柜临时密码怎么查？", count: "8条回复" },
  ],
  circlePosts: [
    {
      id: "bbs-1",
      category: "约伴",
      title: "今晚 8 点环小区慢跑，有没有一起的？",
      content: "路线大概 3 公里，从北门出发绕人工湖一圈，速度很慢，新手也可以来。",
      time: "刚刚",
      author: { name: "阿树", avatar: "assets/avatars/outdoor-man.png" },
      tags: ["跑步", "夜跑", "约伴"],
      replies: [
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "我可以，刚好想恢复运动，8 点北门见。" },
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我先散步跟一段，跑不动就撤。" },
      ],
    },
    {
      id: "bbs-2",
      category: "骑行",
      title: "周日早上骑行去河堤，求不卷的搭子",
      content: "不拼速度，主要晒太阳和喝咖啡。大概 15 公里，带头盔更安心。",
      time: "8分钟前",
      author: { name: "小周", avatar: "assets/avatars/veteran-man.png" },
      tags: ["骑行", "周末", "轻运动"],
      replies: [
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "我家有备用打气筒，出发前可以来借。" },
        { name: "老顾", avatar: "assets/avatars/repair-man.png", text: "河堤西口在修路，建议从南桥绕一下。" },
      ],
    },
    {
      id: "bbs-3",
      category: "赠送",
      title: "家里整理出一袋闲置秋冬衣物，免费自取",
      content: "女装 M 码为主，还有两条围巾。都洗干净了，适合需要的邻居拿走。",
      time: "16分钟前",
      author: { name: "安安", avatar: "assets/avatars/cafe-woman.png" },
      tags: ["闲置", "衣物", "环保"],
      replies: [
        { name: "陈护士", avatar: "assets/avatars/nurse-woman.png", text: "我可以帮你问问社区志愿站有没有需要。" },
        { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png", text: "围巾如果没人要我想拿一条，谢谢。" },
      ],
    },
    {
      id: "bbs-4",
      category: "美食",
      title: "北门新开的牛肉粉有人试过吗？",
      content: "闻起来很香，但是排队有点长。想问问大家推荐哪一款。",
      time: "25分钟前",
      author: { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png" },
      tags: ["美食", "北门", "探店"],
      replies: [
        { name: "阿树", avatar: "assets/avatars/outdoor-man.png", text: "清汤牛肉粉不错，辣椒自己加，汤很舒服。" },
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "晚饭点人多，下午去基本不用排。" },
      ],
    },
    {
      id: "bbs-5",
      category: "环境",
      title: "3 栋楼下垃圾桶旁边味道有点重",
      content: "这两天天热，希望大家厨余袋子扎紧一点，也想问问物业能不能增加清运次数。",
      time: "36分钟前",
      author: { name: "老顾", avatar: "assets/avatars/repair-man.png" },
      tags: ["环境", "物业", "公共空间"],
      replies: [
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "同感，我下午会在业主群里也提醒一下。" },
        { name: "周叔", avatar: "assets/avatars/veteran-man.png", text: "我刚路过看了，桶盖有一个坏了，可以报修。" },
      ],
    },
    {
      id: "bbs-6",
      category: "问答",
      title: "有没有邻居知道附近哪里配钥匙靠谱？",
      content: "想配一把备用门禁钥匙，最好是步行能到的地方。",
      time: "48分钟前",
      author: { name: "陈护士", avatar: "assets/avatars/nurse-woman.png" },
      tags: ["生活问答", "便民", "钥匙"],
      replies: [
        { name: "老顾", avatar: "assets/avatars/repair-man.png", text: "南门外修鞋店可以配，老板手艺还行。" },
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "我上次在那配过，普通钥匙十分钟左右。" },
      ],
    },
    {
      id: "bbs-7",
      category: "亲子",
      title: "周六下午小广场有人带孩子玩飞盘吗？",
      content: "我家孩子想找同龄小朋友一起玩，不比赛，主要跑一跑。",
      time: "1小时前",
      author: { name: "林小乔", avatar: "assets/avatars/teacher-woman.png" },
      tags: ["亲子", "飞盘", "周六"],
      replies: [
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我们下午 4 点左右可以下楼。" },
        { name: "陈护士", avatar: "assets/avatars/nurse-woman.png", text: "天气热，记得带水，小广场树荫还可以。" },
      ],
    },
    {
      id: "bbs-8",
      category: "二手",
      title: "闲置儿童绘本 12 本，想送给低年级小朋友",
      content: "不是交易，书边有一点使用痕迹，但内容完整。需要的邻居可以留言。",
      time: "1小时前",
      author: { name: "小赵", avatar: "assets/avatars/resident-man.png" },
      tags: ["绘本", "赠送", "亲子"],
      replies: [
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "可以放到社区阅读角，孩子们都能看。" },
        { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png", text: "这个主意好，阅读角最近正缺新书。" },
      ],
    },
    {
      id: "bbs-9",
      category: "美食",
      title: "大家觉得小区附近哪家早餐最稳？",
      content: "最近想固定买早餐，包子、豆浆、面都行，主要想少踩坑。",
      time: "2小时前",
      author: { name: "阿杰", avatar: "assets/avatars/resident-man.png" },
      tags: ["早餐", "美食", "推荐"],
      replies: [
        { name: "周叔", avatar: "assets/avatars/veteran-man.png", text: "东门豆腐脑不错，排队快。" },
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我投南门烧麦一票，糯米很香。" },
      ],
    },
    {
      id: "bbs-10",
      category: "环境",
      title: "电动车充电区能不能贴一个排队提示？",
      content: "有时候大家不知道哪辆快充满了，容易误会。想建议做个小提示牌。",
      time: "2小时前",
      author: { name: "周叔", avatar: "assets/avatars/veteran-man.png" },
      tags: ["充电区", "公共秩序", "建议"],
      replies: [
        { name: "老顾", avatar: "assets/avatars/repair-man.png", text: "可以加一个写字板，谁先到谁写时间。" },
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "我赞成，减少误会比吵架强。" },
      ],
    },
    {
      id: "bbs-11",
      category: "约伴",
      title: "想找一个周三晚上羽毛球搭子",
      content: "水平一般，主要出汗。场地可以约附近体育馆 AA。",
      time: "3小时前",
      author: { name: "赵晴", avatar: "assets/avatars/cafe-woman.png" },
      tags: ["羽毛球", "搭子", "运动"],
      replies: [
        { name: "阿树", avatar: "assets/avatars/outdoor-man.png", text: "我可以偶尔参加，提前一天喊我。" },
        { name: "陈护士", avatar: "assets/avatars/nurse-woman.png", text: "体育馆周三人少，比较好订。" },
      ],
    },
    {
      id: "bbs-12",
      category: "灌水",
      title: "今天傍晚的云很好看，像棉花糖",
      content: "从 5 栋楼下抬头看到的，突然觉得小区也挺温柔的。",
      time: "3小时前",
      author: { name: "安安", avatar: "assets/avatars/cafe-woman.png" },
      tags: ["日常", "随手记", "天气"],
      replies: [
        { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png", text: "我也拍了，晚霞那几分钟特别好看。" },
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "这种帖子很治愈，多发。" },
      ],
    },
    {
      id: "bbs-13",
      category: "问答",
      title: "南门快递柜取件码收不到，有人遇到过吗？",
      content: "短信没来，App 里也没有。想问问是不是柜机网络问题。",
      time: "4小时前",
      author: { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png" },
      tags: ["快递", "问答", "南门"],
      replies: [
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "可以点柜机屏幕上的取件异常，会连客服。" },
        { name: "周叔", avatar: "assets/avatars/veteran-man.png", text: "昨天我也遇到过，过十分钟就好了。" },
      ],
    },
    {
      id: "bbs-14",
      category: "赠送",
      title: "多出来一盆绿萝，想送给喜欢养植物的邻居",
      content: "状态挺好，放客厅太挤了。自带小花盆，放窗边就能活。",
      time: "4小时前",
      author: { name: "林小乔", avatar: "assets/avatars/teacher-woman.png" },
      tags: ["植物", "赠送", "生活"],
      replies: [
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我想要，可以放咖啡角旁边。" },
        { name: "老顾", avatar: "assets/avatars/repair-man.png", text: "绿萝耐养，新手友好。" },
      ],
    },
    {
      id: "bbs-15",
      category: "环境",
      title: "楼道灯晚上有点暗，大家有同感吗？",
      content: "特别是 2 栋东侧楼梯口，晚上回来感觉不太安心。",
      time: "5小时前",
      author: { name: "陈护士", avatar: "assets/avatars/nurse-woman.png" },
      tags: ["楼道", "照明", "安全"],
      replies: [
        { name: "周叔", avatar: "assets/avatars/veteran-man.png", text: "这个应该报物业，可能是灯管老化。" },
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "我也遇到过，晚上确实偏暗。" },
      ],
    },
    {
      id: "bbs-16",
      category: "约伴",
      title: "周五晚上有人一起看露天电影吗？",
      content: "听说物业会在中心草坪放一部老片，可以带坐垫和小零食。",
      time: "5小时前",
      author: { name: "阿树", avatar: "assets/avatars/outdoor-man.png" },
      tags: ["电影", "周五", "草坪"],
      replies: [
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我想去，顺便带点自制柠檬茶。" },
        { name: "小鱼丸", avatar: "assets/avatars/pet-woman.png", text: "如果天气好应该很舒服。" },
      ],
    },
    {
      id: "bbs-17",
      category: "美食",
      title: "求推荐附近适合带老人吃饭的店",
      content: "希望清淡一点、座位舒服、不太吵。周末想带爸妈出去吃。",
      time: "6小时前",
      author: { name: "小赵", avatar: "assets/avatars/resident-man.png" },
      tags: ["餐厅", "老人", "推荐"],
      replies: [
        { name: "陈护士", avatar: "assets/avatars/nurse-woman.png", text: "河边那家家常菜还行，少油可以提前说。" },
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "我也推荐那家，包间比较安静。" },
      ],
    },
    {
      id: "bbs-18",
      category: "灌水",
      title: "今天谁家的钢琴声很好听？",
      content: "傍晚听到一小段，很温柔，没有打扰，反而让人心情变好。",
      time: "6小时前",
      author: { name: "赵晴", avatar: "assets/avatars/cafe-woman.png" },
      tags: ["日常", "音乐", "邻里"],
      replies: [
        { name: "林小乔", avatar: "assets/avatars/teacher-woman.png", text: "可能是 6 栋的小朋友，最近在练比赛曲。" },
        { name: "周叔", avatar: "assets/avatars/veteran-man.png", text: "不扰民的练习声，其实挺有生活气。" },
      ],
    },
    {
      id: "bbs-19",
      category: "问答",
      title: "有人知道物业周末几点有人值班吗？",
      content: "想咨询车位登记，平时下班回来他们已经关门了。",
      time: "7小时前",
      author: { name: "老顾", avatar: "assets/avatars/repair-man.png" },
      tags: ["物业", "车位", "问答"],
      replies: [
        { name: "小赵", avatar: "assets/avatars/resident-man.png", text: "周六上午有人，最好 10 点前去。" },
        { name: "陈护士", avatar: "assets/avatars/nurse-woman.png", text: "我上次周日下午去没人，建议别拖到下午。" },
      ],
    },
    {
      id: "bbs-20",
      category: "赠送",
      title: "闲置收纳盒 5 个，搬家后用不上了",
      content: "透明塑料盒，适合放玩具或杂物。有需要的邻居留言，先到先得。",
      time: "8小时前",
      author: { name: "周叔", avatar: "assets/avatars/veteran-man.png" },
      tags: ["闲置", "收纳", "免费"],
      replies: [
        { name: "安安", avatar: "assets/avatars/cafe-woman.png", text: "我需要两个放咖啡角杂物，可以吗？" },
        { name: "老顾", avatar: "assets/avatars/repair-man.png", text: "剩下的可以放工具角收小配件。" },
      ],
    },
  ],
  tools: [
    { id: "tool-1", name: "小推车", owner: "3 栋管家", place: "3 栋大厅", time: "全天可借", rule: "2 小时内免费", price: 0, icon: "cart" },
    { id: "tool-2", name: "折叠梯", owner: "林小乔", place: "5 栋", time: "明天 9:00 后", rule: "实名确认", price: 5, icon: "ladder" },
    { id: "tool-3", name: "工具箱", owner: "物业维修间", place: "物业中心", time: "工作日 9:00-18:00", rule: "物业见证取还", price: 0, icon: "box" },
  ],
  creditProfile: {
    level: "A+",
    title: "高信用邻居",
    summary: "已完成实名、人脸、手机号和小区居住核验。需求方可优先选择高信用接单者，平台会结合认证材料、熟人背书、履约记录和风控事件动态调整分值。",
    metrics: [
      { label: "信用分", value: "96", note: "满分 100" },
      { label: "同小区背书", value: "6 人", note: "越多越可信" },
      { label: "完成互助", value: "23 单", note: "好评持续加分" },
      { label: "近 30 天投诉", value: "0", note: "安全记录良好" },
    ],
  },
  creditProofActions: [
    { id: "identity", title: "上传实名人脸与居住材料", desc: "身份证实名、人脸核验、房产证或租房合同、小区楼栋房号。", score: "+30", tag: "基础准入" },
    { id: "certificate", title: "上传个人有效证书", desc: "教师证、护士证、幼师证、退伍证、宠物医师证、护工证等。", score: "+6~12", tag: "持证优先" },
    { id: "neighbor", title: "邀请本小区居民认证", desc: "同小区注册用户为你背书，认证人数越多，信用分越高。", score: "+2/人", tag: "熟人背书" },
    { id: "record", title: "上传无犯罪记录证明", desc: "涉及人身安全、入户隐私、财产资金、需要专业资质部分服务。", score: "+15", tag: "高风险权限" },
  ],
  creditRules: [
    {
      title: "一、信用分怎么增加",
      points: [
        "实名登录、身份证正反面、人脸比对、手机号认证通过后获得基础分。",
        "上传房产证或租房合同并填写小区楼栋房号，确认本小区居住身份后继续加分。",
        "上传教师证、护士证、幼师证、退伍证、宠物医师证、护工证等有效证书，可获得专业可信标签。",
        "同小区居民为你完成熟人认证，每增加一名有效认证人，信用分递增。",
        "完成服务后获得好评、准时履约、无投诉，会持续增加信用分。"
      ],
    },
    {
      title: "二、接单者准入与试用期",
      points: [
        "所有接单者必须完成微信或手机号实名登录、身份证实名、人脸比对和居住核验。",
        "接送孩子、老人陪护等高风险服务需要上传无犯罪记录证明，平台人工复核。",
        "有暴力、盗窃、故意伤害、虐待、猥亵等相关记录者永久禁止高风险接单。",
        "新接单者前 5 单只开放取快递、物品共享、遛宠等低风险订单，全好评后逐步开放更高权限。"
      ],
    },
    {
      title: "三、分场景安全规则",
      points: [
        "接孩子必须提交监护授权、孩子信息、固定交接点、交接照片和 GPS 轨迹。",
        "老人陪护必须绑定家属紧急联系人，夜间不开放独居老人上门陪护订单。",
        "遛宠、跑腿、维修等通用服务必须记录轨迹和完成照片，宠物伤人或物品损坏按协议处理。",
        "接单者不得私自绕路、带孩子逗留、进入接单者家中或给孩子零食饮料。"
      ],
    },
    {
      title: "四、资金保险与证据留存",
      points: [
        "付费订单资金走平台托管，完成节点照片和需求方确认后再结算。",
        "平台可为订单配置短期意外险和第三方责任险，用于服务途中意外、宠物伤人、老人摔倒等风险。",
        "高风险服务可要求接单者缴纳小额服务押金，重大纠纷时优先用于前期赔付。",
        "定位轨迹、录音、交接照片、电子签名和聊天记录云端留存不少于 6 个月。"
      ],
    },
    {
      title: "五、扣分与封禁",
      points: [
        "轻微违规，如私自带孩子买零食，警告并限制 3 天高风险订单。",
        "出现安全投诉、路线偏离、宠物伤人等事件，永久关闭接娃和上门陪护权限。",
        "出现人身伤害、虐待、盗窃等重大投诉，直接封号并配合警方调查。",
        "需求方同样需要完成住址核验，防止外来人员骚扰本小区居民。"
      ],
    },
  ],
  creditRanking: [
    { rank: 1, name: "林小乔", score: 99, label: "退休教师 · 12 人背书", avatar: "assets/avatars/teacher-woman.png" },
    { rank: 2, name: "周叔", score: 98, label: "退伍军人 · 维修好评", avatar: "assets/avatars/veteran-man.png" },
    { rank: 3, name: "陈护士", score: 97, label: "护士证 · 老人陪护", avatar: "assets/avatars/nurse-woman.png" },
    { rank: 4, name: "小赵", score: 96, label: "实名居住 · 零投诉", avatar: "assets/avatars/resident-man.png" },
    { rank: 5, name: "阿树", score: 95, label: "活动组织者 · 准时履约", avatar: "assets/avatars/outdoor-man.png" },
    { rank: 6, name: "安安", score: 94, label: "咖啡角共建 · 8 人背书", avatar: "assets/avatars/cafe-woman.png" },
    { rank: 7, name: "小鱼丸", score: 93, label: "宠物友好 · 遛宠好评", avatar: "assets/avatars/pet-woman.png" },
    { rank: 8, name: "老顾", score: 91, label: "工具共享 · 物业见证", avatar: "assets/avatars/repair-man.png" },
  ],
};
